spring:
  application:
    name: stylo-shopping-mall

  datasource:
    url: jdbc:postgresql://localhost:5555/stylo
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  # 세션 설정
  session:
    timeout: 30m # 30분

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jooq:
    sql-dialect: postgres

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /

# 로깅 설정
logging:
  level:
    project.stylo: INFO
    org.springframework.security: INFO
    org.jooq.tools.LoggerListener: DEBUG

# MinIO 설정
minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:root}
  secretKey: ${MINIO_SECRET_KEY:root1234}
  bucket: ${MINIO_BUCKET:stylo-bucket}

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method